### ISSUE TITLE
How do I add a Function to a Module?

### ISSUE THREAD

**Issue by SunDoge** [carllerche/codegen#14]
The `Module` has a `Scope`  with a `Vec` of `Item`, but there is no `Function` in the `Item`, so the only way to push a `Function` to `Module` is to turn it into a `String`, right? 

Perhaps `Item` should include `Function`, which would make it much more easier.

**Comment by carllerche** [comment]
I would consider using `syn + quote + rustfmt` as an alternative to codegen. These projects are better maintained.

**Comment by rivertam** [comment]
I would caution anyone about taking the above advice too seriously. [quote](https://github.com/dtolnay/quote) seems to be useful for procedural macros, but not ad-hoc code generation. It can do some basic stuff, but I basically just went a rabbit-hole trying to solve this problem using `quote` where I believe `codegen` does a much better job. It has imperfections (such as this one), but it's way easier to reason about for this use-case in my opinion. At least if this is your only issue with the project, I'd just turn it into a string and raw interpolate it. You're going to have to do that with `quote` anyways.

**Comment by carllerche** [comment]
What issue did you hit with syn + quote?

**Comment by rivertam** [comment]
Creating new identities was either very difficult and under-documented or impossible, and as far as I can tell it's the only way to get reasonable output. `quote` expects you to use quite structured interpolated variables, usually gotten from the already extant syntax tree (that the proc macro is running on). Strings result in escaped strings (so `let #var` becomes `let "var"`, not `let var`), and I don't think there's a way to avoid that. I had this all pulled up yesterday but I'll just give you the gist:

- The way you're supposed to create new identities involves the syn/proc-macro `Ident`
- When asked about requiring to be on `proc-macro`, the author said something like how you can use proc-macro2 to just get the `Ident` type, and you don't need anything actually from proc-macro but that type
- However, since that comment and now, the `Ident` type lost its constructor that just takes a string, so now it requires a `Span`...

I think I got further than that, but at the end of the day I realized how crazy I was being and how I should just fake it with text templates. I don't need this stuff to be beautiful and elegantly written using the latest and greatest or whatever. I'd rather use a poorly maintained library like this one, or just template strings, than have to jump through all these hoops.

Sorry, not trying to rant or sound bitter or anything at all. `quote` is a great library for its purpose, and `codegen` is pretty great too. Just saying I don't think `syn` and `quote` are good for this usecase.

**Comment by carllerche** [comment]
@rivertam Since it sounds like you depend on this lib, I added you as a collaborator ;)

**Comment by rivertam** [comment]
Haha thanks. Will contribute if I modify it.

For the record, I wasn't really trying to push you to fix this. Just leaving a word of caution for those who might want to follow the wormhole I'd gone down. But it's a cool library anyways.
